steps:
# Step 1: Build the Docker container image.
# We change directory into 'my-todo-app/backend' to find the Dockerfile.
- name: 'gcr.io/cloud-builders/docker'
  dir: 'my-todo-app/backend' # <-- THIS IS THE ONLY LINE THAT NEEDED TO CHANGE
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${REPO_NAME}-backend:$COMMIT_SHA', '.']

# Step 2: Push the container image to Google Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${REPO_NAME}-backend:$COMMIT_SHA']

# Step 3: Deploy the new container image to Cloud Run.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-todo-backend-service' # Service name for the backend
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${REPO_NAME}-backend:$COMMIT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${REPO_NAME}-backend:$COMMIT_SHA'

substitutions:
  _REGION: 'asia-south1'
  _AR_REPO_NAME: 'my-apps'

options:
  logging: CLOUD_LOGGING_ONLY
